#!/usr/bin/env python

import rospy
import rosbag
from geometry_msgs.msg import Twist
from std_msgs.msg import Float64
import random

def main():
    rospy.init_node('velocity_noise_publisher')
    
    input_bag = '2023-08-27-17-22-31.bag'  
    output_topic = '/noisy_velocity'
    noise_stddev = 0.1  
    bag = rosbag.Bag(input_bag)
    output_pub = rospy.Publisher(output_topic, Float64, queue_size=10)
    
    for topic, msg, t in bag.read_messages(topics=['/cmd_vel']):
        if isinstance(msg, Twist):
            linear_velocity = msg.linear.x
            noisy_velocity = linear_velocity + random.gauss(0, noise_stddev)
            output_pub.publish(noisy_velocity)
            rospy.loginfo("Noisy Velocity: %f", noisy_velocity)
            rospy.sleep(0.1)
    
    bag.close()

if __name__ == '__main__':
    try:
        main()
    except rospy.ROSInterruptException:
        pass
